version: '2.1'
services:
  express_api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: express_api
    user: node
    working_dir: /home/node/app/api
    volumes:
      - ./:/home/node/app
    ports:
      - 7770:7770
    environment:
      - POSTGRES_HOST=database
    depends_on:
      - database
    env_file:
      - ./api/.env
  react_client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: react_client
    working_dir: /home/node/app/client
    volumes:
      - ./:/home/node/app
    ports:
      - 7771:7771
    env_file:
      - ./client/.env
  database:
    image: postgres:9.6
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 7772:5432
    env_file:
      - ./api/.env
volumes:
  database:
